name: CI

on:
  push:
    branches: [ cypress ]
  pull_request:
    branches: [ cypress ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: andrehil/simple-node-ci@main
      with:
        node-version: lts/*
        integration-test-lib: 'cypress'
        integration-test-command: npm run test:cy
