name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: andrehil/simple-node-ci@main
      with:
        node-version: lts/*
